language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - addon-google_apis-google-22
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
 - chmod +x gradlew

deploy:
  provider: releases
  api_key:
    secure: V1TtRfwhYm7dRRDEUnLMs0t5vIymnIMd/+DtuEvNzgBt4+Vtn7VcWzw2gmEg1UTnwTeDBOuzUZKmBslJ9B4Ts0pUaqNmWcD+8EDs3s58QFFTY3OT6ZVG/V84xyLg0b/bRhAD9/9UZuJuHbf9Y/29IvysUAKXG7nsUHXRFFtSZlg=
  file: ${TRAVIS_BUILD_DIR}/app/build/outputs/apk/app-release.apk
  on:
    repo: alaendle/outdooractive-examples
    tags: true
