language: scala
scala:
- 2.11.6
jdk:
- oraclejdk7

before_install:
# Install base Android SDK
- sudo apt-get update -qq
- sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
- export COMPONENTS=build-tools-22.0.0,android-22,addon-google_apis-google-22,extra-google-m2repository
- curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
- source ~/.android-sdk-installer/env
